### ISSUE TITLE
The type or namespace name '(stuff)' could not be found

### ISSUE THREAD

**Issue by KisuWolf** [chrysls/scp-mono-internal#1]
I'm just going to start it off as I'm shit at coding.
Alright so when I grab these files, go into VS and try to build the Injector it works. But when I try to build ExampleAssembly, it starts giving me 'The type or namespace name '(insert stuff here ex: Camera, UnityEngine) could not be found (are you missing a using directive or an assembly reference?)
I kind of get what it means, but I don't know how to fix this.
Thanks.
P.S I have FASM.NET and Process.NET and their correct versions. (Shouldn't relate to this as those are for injector right?)

**Comment by chrysls** [comment]
Links are broken. I installed unity3d to make things work, you can select
from game folder.
вс, 25 февр. 2018 г. в 17:31, KisuWolf <notifications@github.com>:

**Comment by chrysls** [comment]
![default](https://user-images.githubusercontent.com/11868838/36642935-cfa5504e-1a56-11e8-869a-267e40c1d6ee.jpg)
Links.

**Comment by KisuWolf** [comment]
Uh, I don't know if I did this right but that didn't work. (I can safely say I probably did something wrong with the linking)
What I did was select ExampleAssembly, opened data sources, went to object, clicked add reference, went to browse, found those things that you showed above, added them, pressed ok, went back to select data objects and selected them again, and pressed finish.
