### ISSUE TITLE
how me aplly the hack

### ISSUE THREAD

**Issue by idkdud** [chrysls/scp-mono-internal#10]
hello how me apply this hack its in the file of the game idk can you make a tutorial o the correct file idk how to aplly

**Comment by chrysls** [comment]
This hack is outdated and injector is not working (game closes itself).
Check new version at https://github.com/chrysls/scp-external

**Comment by idkdud** [comment]
but how me aplly this

hack pls



________________________________
De: chrysls <notifications@github.com>
Enviado: quinta-feira, 2 de agosto de 2018 05:59
Para: chrysls/scp-mono-internal
Cc: idkdud; Author
Assunto: Re: [chrysls/scp-mono-internal] how me aplly the hack (#10)


This hack is outdated and injector is not working (game closes itself).
Check new version at https://github.com/chrysls/scp-external

[https://avatars3.githubusercontent.com/u/11868838?s=400&v=4]<https://github.com/chrysls/scp-external>

chrysls/scp-external<https://github.com/chrysls/scp-external>
github.com
scp-external - External hack for SCP Secret Laboratory (actually internal as it just writes to memory, but I will add esp one day :D)

**Comment by chrysls** [comment]
:thinking: currently there's no way to do it.

**Comment by chrysls** [comment]
> but how me aplly this hack pls
> […](#)

Updated injector, get it at [uc](https://www.unknowncheats.me/forum/downloads.php?do=file&id=24716)
