### ISSUE TITLE
[Injector] Fix ready

### ISSUE THREAD

**Issue by chrysls** [chrysls/scp-mono-internal#11]
Fixed the injector (kind of).
I will upload new version soon. It can bypass protection so you can inject any mono-dll.

https://i.imgur.com/rd8zLWX.png

**Comment by theclashingfritz** [comment]
I'm curious then, What protections do they use to prevent this? If it's simple it should be possible to use a unity .dll as a hook entry point and force our way in.

**Comment by chrysls** [comment]
The first injector was public and they fixed it.
I waited them to fix new injector, but they didn't. I can't make it public to save my personal time.
