### ISSUE TITLE
Как слышать всех?

### ISSUE THREAD

**Issue by SileBro** [chrysls/scp-mono-internal#13]
Я нашел строчку с комментарием о radio но когда компилируешь говорит что не найдено, как быть? Пофиксили?

**Comment by chrysls** [comment]
Я не доделал. Там нужно патч памяти, ну или изменения в AssemblyCsharp.dll игры

**Comment by SileBro** [comment]
Эх((

**Comment by chrysls** [comment]
В новую версию чита добавлена опция, чтобы слышать всех.
