### ISSUE TITLE
Как сделать ESP 914, теслы и генераторов?

### ISSUE THREAD

**Issue by SileBro** [chrysls/scp-mono-internal#19]
У них тег untagged, просто написать untagged в теге не помогает.

**Comment by chrysls** [comment]
Это уже добавлено в последнюю версию, которая не загружена. ФПС падает дико, если включать эту пасту с Beethoven :)
Внёс немного оптимизации, всё ещё не круто, включаю на пару секунд и отключаю, иначе фризы идут.

**Comment by SileBro** [comment]
Окей, буду ждать новую версию
