### ISSUE TITLE
compiled with VS. 

### ISSUE THREAD

**Issue by dawgsxrules** [chrysls/scp-mono-internal#2]
As a total noob that knows nothing about how do this, then how would i do this.
cuz when i run it in vs. i don't see any ExampleAssembly.dll

**Comment by chrysls** [comment]
![default](https://user-images.githubusercontent.com/11868838/36698927-49f6511c-1b5c-11e8-9e14-2522a3b9f4f6.jpg)
You should compile both projects and use only Injector one.

**Comment by dawgsxrules** [comment]
https://www.youtube.com/watch?v=UKE-r6CIIkA&feature=youtu.be
Alright this what i'm doing. i'm most likely dumb and doing this all wrong

**Comment by chrysls** [comment]
Uploaded compiled version. But windows defender will tell you that is a suspicious program (Injector itself).

**Comment by GitRub69** [comment]
Hey, could you release another compiled version, I'm having troubles compiling.

**Comment by chrysls** [comment]
Ok, I'll make a video how to compile.

**Comment by chrysls** [comment]
Check main page of this repo for video about compiling.
