### ISSUE TITLE
HELP

### ISSUE THREAD

**Issue by DeathPhoenix303** [chrysls/scp-mono-internal#23]
How do i update it ... i alredy read the thing

**Comment by SileBro** [comment]
Stupid... Compile Example Assembly, rename to hack.dll and copy to the folder with injector.exe. Run game, run injector.exe

**Comment by SileBro** [comment]
Injector: https://www.unknowncheats.me/forum/downloads.php?do=file&id=25445

**Comment by HarryAwesome06** [comment]
> 
> 
> Stupid... Compile Example Assembly, rename to hack.dll and copy to the folder with injector.exe. Run game, run injector.exe
and how would you Compile the folder? Can we have an explanation? (The video didn't help and I searched how to convert a folder to a dll to no avail.

**Comment by chrysls** [comment]
> > Stupid... Compile Example Assembly, rename to hack.dll and copy to the folder with injector.exe. Run game, run injector.exe
> 
> How would you compile the folder? Can we have an explanation? (The video didn't help and I searched how to convert a folder to a dll to no avail.

You should use [Visual Studio](https://visualstudio.microsoft.com/en/downloads/) and follow video-guide at [YouTube](https://www.youtube.com/watch?v=ls381bjXmf4).

**Comment by chrysls** [comment]
And check this Check this https://github.com/chrysls/scp-mono-internal/issues/25
