### ISSUE TITLE
Completely confused on how to make it

### ISSUE THREAD

**Issue by guccisteve** [chrysls/scp-mono-internal#24]
How the hell do I compile it? I've been trying for like 3 hours and still made no progress. Can I please get an explanation on how to do it, and install it, that'd be great! A step by step explanation anyways. I've also already watched the video and it was no help to me. could someone just send me the dll in a .zip file instead? Anyways, cheers!

**Comment by HarryAwesome06** [comment]
https://www.unknowncheats.me/forum/downloads.php?do=file&id=25445
Download that, then run it. You should not have to compile it.

**Comment by chrysls** [comment]
Check this https://github.com/chrysls/scp-mono-internal/issues/25
