### ISSUE TITLE
Идея

### ISSUE THREAD

**Issue by SileBro** [chrysls/scp-mono-internal#26]
Я заметил что в игре есть много багов с моделькой, как по мне можно сделать много интересных функций с этим. К примеру FakeAnim - фейковая анимация игрока, к примеру в игре есть странная анимация прыжка. Когда игрок сгибает коленки и подпрыгивает. Её можно использовать. Так же можно попробовать сделать FakePos - фейковую позицию игрока, когда у игроков моделька стоит в одном месте, а для читера он в другом месте. Попробуйте реализовать пожалуйста.

**Comment by chrysls** [comment]
Уже реализовано ведь, остановка отправки пакетов (G \ H кнопки).
Если ты хочешь, чтобы игрок отображался в другом месте, и не получал урон при этом, то вряд ли, так как урон отправляется через клиент игрока, а не просчитывается сервером.
То есть, каждый сам отправляет, попал он в голову или промазал. Никакой баг анимации не поможет, если у второй игрок отправит данные "я попал".

**Comment by t1f7** [comment]
#32
