### ISSUE TITLE
Детект подкрался незаметно 

### ISSUE THREAD

**Issue by zacker3** [chrysls/scp-mono-internal#28]
Теперь любые читы ушли в детект и при запуске почти сразу (примерно через 10-15 минут) прилетает steam бан на игру. Либо это я где то накосячил. До этого всё работало отлично.

**Comment by chrysls** [comment]
Кто-нибудь ещё может подтвердить это? Или ситуация уникальна?

**Comment by zacker3** [comment]
В комментариях в теме Revolution на UnknownCheats есть люди которые тоже писали что то про global ban. Я видел тех кто читерит, кажется баны даются, но не всем.

**Comment by zacker3** [comment]
Когда играешь без читов с нового аккаунта - бана нет. Как только заходишь на сервер и читы заинжекчены - пишет что то про то, что вы были забанены за использование стороннего по. И бан идёт в steam. Могу прислать ссылки на пустышки с этим баном. Красная табличка в профиле сразу вешается.

**Comment by zacker3** [comment]
Пишет "You have been globally banned: You are banned for a using a thrid party program" 
Вот один из профилей на котором я пытался читерить https://steamcommunity.com/profiles/76561198885834458/

**Comment by zacker3** [comment]
Пардон. Дело было в unlock atchivments модуле, разработчик добавил его детект и теперь он не работает. Просто юзаю твой инжектор и часть твоих функций, а так же взял пару функций с revolution.
