### ISSUE TITLE
Фиксанули FindLocalPlayer() 

### ISSUE THREAD

**Issue by Fsbeshka** [chrysls/scp-mono-internal#30]
Привет. Читы outdated так как findlocalplayer фикс и даёт null. Я овощ в программировании и умею только пастить чужое, поэтому прошу тебя посмотреть и обойти защиту.

**Comment by Fsbeshka** [comment]
Речь шла об обнове на перовое апреля. Сейчас уже обнова даунгрейднута и всё по старому, но я уверен что новый серверный код и фикс локал плеера снова появятся уже в грядущей обнове.

**Comment by chrysls** [comment]
Самое простое, что ты можешь сделать - задавать localPlayer из ESP отрисовки (дистанция до самого себя всегда 0).
