### ISSUE TITLE
Bunch of shit

### ISSUE THREAD

**Issue by 64Evolution** [chrysls/scp-mono-internal#4]
Whenever I attempt to build/rebuild the stuff I get these "Warnings" and it doesn't actually do anything more: [![Screenshot from Gyazo](https://gyazo.com/b185f798a7c0f1a8d88d18d6570ec475/raw)](https://gyazo.com/b185f798a7c0f1a8d88d18d6570ec475)

**Comment by chrysls** [comment]
I got the same error when I switched it to x64.
The game is running in x32, and hack also must be x32, ok?

**Comment by 64Evolution** [comment]
How abouts would I do that?

**Comment by chrysls** [comment]
![githubhsit](https://user-images.githubusercontent.com/11868838/37196064-5d977e4e-2386-11e8-9180-3564eaced24c.jpg)

**Comment by 64Evolution** [comment]
Alright I’ll give it a try tomorrow, thank you for the assistance!

**Comment by 64Evolution** [comment]
After trying the Prefer 32 bit setting, It was already enabled and I still get the errors with it on or off.

**Comment by chrysls** [comment]
Screenshot full project please.

**Comment by 64Evolution** [comment]
[![Screenshot from Gyazo](https://gyazo.com/e257fdfe30293bbd010b85e38f3488bb/raw)](https://gyazo.com/e257fdfe30293bbd010b85e38f3488bb)

**Comment by chrysls** [comment]
Try to set manually "Any CPU" to "x86"

**Comment by 64Evolution** [comment]
That removed the one but leaves these[![Screenshot from Gyazo](https://gyazo.com/ba56fc0b4cf5c6680a55cc3307872816/raw)](https://gyazo.com/ba56fc0b4cf5c6680a55cc3307872816)

**Comment by chrysls** [comment]
That's a warnings you should not care about.
What do you mean "doesn't seem to work".
You compiled, injected in game and there's nothing changed or what?

**Comment by 64Evolution** [comment]
I believe I did I may just be doing it wrong but nothing changes.

**Comment by 64Evolution** [comment]
So as it seems I was just doing it wrong, However, on the injector, I am now getting this error [![Screenshot from Gyazo](https://gyazo.com/aaef08a6b12f1c86d42c092852bf2c35/raw)](https://gyazo.com/aaef08a6b12f1c86d42c092852bf2c35)
