### ISSUE TITLE
inject help

### ISSUE THREAD

**Issue by joshua161616** [chrysls/scp-mono-internal#5]
![capture](https://user-images.githubusercontent.com/37497051/37563929-a41ccbf2-2adf-11e8-8fe3-a2e6fea07baa.PNG)
what do i do

**Comment by chrysls** [comment]
1. Start game and press Refrash if there's no process in list.
2. Select your compiled dll.
3. ExampleAssembly
4. Loader
5. Load
6. Inject.

**Comment by joshua161616** [comment]
but i only made a exe not a dil
