### ISSUE TITLE
Update is coming

### ISSUE THREAD

**Issue by t1f7** [chrysls/scp-mono-internal#8]
Update is coming.
Fixed hack so it works with latest version.
Removed a lot of options as I'm not going to support them (class change as well).

Upcoming features:

1) Disable door collisions - you don't care if door is closed, right?
2) Fix noclip (WIP).
3) Disabling death triggers (WIP).
Sometimes when you noclip you can enter into death trigger. Why would you care about that if death trigger is client-side only? The same with wrong "doors" at pocket dimension.
4) Working aimbot (WIP)

**Comment by Trisks** [comment]
when is the update coming out? Thanks

**Comment by chrysls** [comment]
When I would like to play that game again. Very low online, not enough players \ fun. Cheating makes no sence if there's not enough players.

**Comment by SileBro** [comment]
Hello! Your previous version of the cheat was very good, I'm looking forward to the new one. You wrote that the game is very low online, but I do not think so, Russian servers almost always have online and you can have fun. Thanks for your cheats.

**Comment by Yalafreed** [comment]
Hello, chrysls
You have very good cheat
, I was able to do it - that I tried to help you in any way
as I in it don't rabiratsya at all, I can't compile v0.9 scp hack in any way, help please
or give dll at least, I ask.
I Russian people
 and bad know English

**Comment by Yalafreed** [comment]
А вы русский
Вы еще делали скрипты на Dota 2 hake.me
Я вас вспомнил
Честно, у вас очень крутой чит на SCP
но я не могу им пользоваться, так как у меня какие то ошибки в коде, ссылки на dll файлы стоят
а вот с кодом проблемы
![image](https://user-images.githubusercontent.com/40443136/41747681-849b64d2-75b7-11e8-8b39-aae6bba3eb25.png)
Если вам не сложно, то помогите, пожалуйста

**Comment by chrysls** [comment]
> у меня какие то ошибки в коде
Ты можешь закомментировать участки кода, которые вызывают ошибки. Полностью оружие было переделано - всё, что с ним связано, можно удалить.
Часть классов переименована, не помню точно, что убрать нужно. Их просто сократили немного.

**Comment by Yalafreed** [comment]
Сможете dll скинуть?
или проект скинуть переделанный
пожалуйста, прошу..

**Comment by Yalafreed** [comment]
Я отредактировал, но теперь не работает сам injector (он не видит игру)
а если другие инжекторы использовать - то игра крашится

**Comment by Yalafreed** [comment]
Как с вами можно связаться?

**Comment by Yalafreed** [comment]
Помогите пожалуйста, MonoInjector Sharp не работает, (не видит процесс игры)

**Comment by chrysls** [comment]
Обсуждения проходят тут: https://www.unknowncheats.me/forum/other-fps-games/286311-scp-sl-using-mpfatxds-dll-update.html

Кратко: игра перешла из 32 в 64 бит.

**Comment by Yalafreed** [comment]
Может это у меня только такая ошибка, но SharpMonoInjector не видит процесса SCPSL.exe

**Comment by Yalafreed** [comment]
Вот допустим игру Totally Accurate Battlegrounds он видит, а SCP SL нет(((

**Comment by chrysls** [comment]
А ты точно скомпилировал под x64 инжектор и чит?

**Comment by Yalafreed** [comment]
Точно
если что еще раз попробую

**Comment by Yalafreed** [comment]
Все dll исходники на эту игру написаны в 32x поэтому и инжекторы не работают так скажем

**Comment by Yalafreed** [comment]
Может у меня что то с виндой не так, но у меня некоторые инжекторы не видят процесса игры

**Comment by DigloBo** [comment]
Когда новая версия читов будет готова?

**Comment by chrysls** [comment]
Как настроение будет. Я пока что с овервотчем балуюсь :)

**Comment by Yalafreed** [comment]
Крч, вместо использования каких то либо dll читов, просто изменил через dnSpy 
Assembly-CSharp.dll  убрал там отдачу, за скромника сделал скорость как у ракеты) и т.д
вот сейчас ищу в Assembly-CSharp.dll как изменить использования дверей с далека, только вот не знаю как

**Comment by DigloBo** [comment]
Буду ждать

**Comment by chrysls** [comment]
@Yalafreed 

> как изменить открытие дверей с далека, только вот не знаю как

Там есть событие приходящее с сервера, чтобы синхронизировать двери между клиентами. Либо оттуда копать внутрь дверей (что-то вроде doorState), либо принудительно игнорировать закрытие двери, тогда двери будут открываться, но не будут закрываться.

**Comment by Yalafreed** [comment]
Блинн
сделайте побыстрей чит пожалуйста
просто очень хочется вх либо проходить сквозь двери, или с далека открывать и т.д
А кстати вх на комнаты в "Легкой зоне" где D-CLass спавниться
чтобы можно было видеть где комната scp-914, оружейная, туалет, офис, чекпоинт и т.д
просто если бы я разбирался, то давно как нибудь сделал
а так пытаюсь изменить файл игры, не понимая что делаю

**Comment by chrysls** [comment]
Вчера вечером провёл несколько экспериментов. Пока что так себе.
Судя по всему, они добавили некую защиту от инжекта, нужно обходить.
То есть, инжектор уже видит игрушку, но на этапе внедрения dll игра закрывается. Да и байт-код странный очень у mono_image_load или как оно там.

**Comment by DigloBo** [comment]
Я рад что ты не забросил читы и смотришь что можно сделать. Спасибо.

**Comment by Yalafreed** [comment]
Согласен)

**Comment by chrysls** [comment]
Ну сделал временный микро-хак. Отключает отдачу и передачу сигнала шага. То есть, бегаете как скрытный ниндзя, и не мажете (почти).

**Comment by Yalafreed** [comment]
dll инжектор?
или Assembly-CSharp изменил?

**Comment by chrysls** [comment]
Память игры. Без инъекции и изменения исходного кода.

**Comment by Yalafreed** [comment]
К сожалению не понимаю о чем речь
первый раз об этом слышу

**Comment by chrysls** [comment]
За деда особенно весело играть, если твои шаги не слышно другим игрокам :D

**Comment by DigloBo** [comment]
Круто. А можешь выложить в сюда или на яд?

**Comment by DigloBo** [comment]
Круто. Можешь залить на ют туториал как это делать?

**Comment by chrysls** [comment]
Лучше. Я почти доделал C++ чит, который автоматически всё подменит.
Ну позже ещё и ESP через него будет.

**Comment by DigloBo** [comment]
Есть идейка что можно сделать. Авточекер админов на сервере, что бы если на сервере будет появляться игрок с ником красного цвета читеру будет выводиться куда то предупреждение. Очень поможет.

**Comment by Yalafreed** [comment]
Ждуу с нетерпением !!!!!!

**Comment by chrysls** [comment]
Да они издеваются! Опять обновление.. Сейчас посмотрю, всё ли работает..

**Comment by Yalafreed** [comment]
Ждуу!!!!
хывахыв
пж постарайся, спасибо тебе, правда)

**Comment by chrysls** [comment]
[)Загрузил](https://www.unknowncheats.me/forum/2167830-post134.html скомпилированный чит.  Инструкции в описании.

**Comment by Yalafreed** [comment]
Сможешь тут писать об обновление этого чита?

**Comment by chrysls** [comment]
[Версия 0.2](https://www.unknowncheats.me/forum/2169720-post141.html), теперь с валлхаком.
![zombie fucker](https://user-images.githubusercontent.com/11868838/42413649-352f67d6-822d-11e8-8f3c-a4547f63e528.png)

**Comment by DigloBo** [comment]
Скоро протестирую.

**Comment by DigloBo** [comment]
А, он на модерации, нельзя скачать :/

**Comment by DigloBo** [comment]
Только что встретился читер с ником "scp 1337". Гениальный читер с "крутилкой", аимом, esp и по моему noclip. Зато отключения шагов нету:D

**Comment by DigloBo** [comment]
Я тоже удивился...

**Comment by DigloBo** [comment]
Прошло 17 часов с момента публикации чита а его до сих пор не проверили и не утвердили, как так то?

**Comment by DigloBo** [comment]
Можешь загрузить свой чит на файлообменник? Например, на яндекс диск.

**Comment by Yalafreed** [comment]
Можно google disk файлообменник?

**Comment by DigloBo** [comment]
О, разблочили скачивание. Сейчас посмотрю.

**Comment by Yalafreed** [comment]
у меня только после респавна, за другой класс работает вх

**Comment by chrysls** [comment]
По ссылке инструкция ведь есть. Если вх с перебоями, то запустить чит ещё раз. В новой версии это исправлено, но я ещё тестирую.

**Comment by Yalafreed** [comment]
Я вкурсе, но я так делал, все равно 0 реакции
Если бы, вы могли скинуть свою новую версию сюда, то может это исправит мою проблему
Заранее спасибо

**Comment by chrysls** [comment]
[Version 0.3, bug-fixes](https://www.unknowncheats.me/forum/other-fps-games/289736-scp-sl-external-hack.html)

**Comment by DigloBo** [comment]
Как отключить коллизию у дверей?

**Comment by chrysls** [comment]
Это не будет работать.
Отключение коллизии на клиенте не отключит её на сервере.
Если ты хочешь проходить сквозь двери, то нужно использовать более хитрые комбинации.
Например: упасть под пол, пройти расстояние двери, подняться наверх.

**Comment by DigloBo** [comment]
Странно... Встречал сегодня ночью (по МСК) одного человека, он без проблем и хитростей проходит сквозь все двери, на вопрос: "Как?" отвечал что изменяет код игры.

**Comment by DigloBo** [comment]
Есть один баг, при запуске чита сначала запускается патч камеры и только после патч wallhack. Поэтому камера не патчится и читы приходиться перезапустить. Необходимо сначала запускать патчер wallhack и уже после патчить камеру.

**Comment by Yalafreed** [comment]
chrysls Здравствуйте, я тут нашел новый чит на эту игру https://youtu.be/dVGPxk2QWDI
Вот, а там есть встроенная функция чтобы слышать всех на сервере, а так же SCP и т.д
(этот человек скинул чит файлом Assembly-CSharp)
Я бы хотел узнать, как можно отключить общий чат, я просто в этом не шарю как то

**Comment by Yalafreed** [comment]
А я понял в типе "Radio" нужно все изменить

**Comment by DigloBo** [comment]
yalafreed ты случайно не админ одного сервера? Просто сегодня ночью видел одного администратора с таким ником)) Он наше пати с эссипи разогнал, нормально общались, говорили друг с другом, прикалывались а он (ты) прилетел, поговорил с нами и рестартнул сервак.

**Comment by chrysls** [comment]
> он без проблем и хитростей проходит сквозь все двери

Хз, я даже удалял двери, пройти не мог. Возможно, на данном сервере слабее защита (отключена проверка коллизии для всех или для админов).

> Необходимо сначала запускать патчер wallhack и уже после патчить камеру.

Это не баг, а необходимость. Смысла от wallhack нету, если каждая твоя пуля летит в тебя же.

> Я бы хотел узнать, как можно отключить общий чат, я просто в этом не шарю как то

Отключить общий чат? Не понимаю, зачем это, но можешь просто в настройках игры установить громкость войс чата на 0.

### Известные баги, которые вряд ли будут пофикшены

* На Windows 7 чит вызывает краш игры.

### Known bugs that won't be fixed probably

* Hack crashes the game with Windows 7

**Comment by Yalafreed** [comment]
А какой у тебя ник был?

**Comment by Yalafreed** [comment]
chrysls, А как с вами можно сотрудничать, я бы хотел сделать свой сервер в этой игре
мне бы понадобилась ваша помощь, можно будет договориться, ток не дорого если)
чтобы у меня и на хостинг хватило

**Comment by chrysls** [comment]
@Yalafreed в дискорде добавься в https://discord.gg/ZpRpMp, так обещали помогать русскоязычному сегменту по этой игре

**Comment by DigloBo** [comment]
Ник свой говорить я не буду, да и не помню, меняю их каждые часа 3. Я тоже кстати сервер создавать планирую))

**Comment by Yalafreed** [comment]
Не переживай
я тея банить не буду
наоборот пообщаться хотел

**Comment by DigloBo** [comment]
Так ты все таки был администратором данного проекта?)

**Comment by DigloBo** [comment]
Добавь меня в дискорд, там пообщаемся. Matthew Pro
#2085

**Comment by DigloBo** [comment]
Мне бан в игре выдали, да прям так, что аж в стим пишет что у меня бан. Благо это обходиться обычным созданием нового аккаунта.

**Comment by DigloBo** [comment]
Как оказалось все баны на серверах в игре можно обходить очень просто, создать новый аккаунт и входить в scp с впн.
